OutputFolder_PATH:    C:/BurnedAreaStats/output/
BurnedAreas_PATH:     C:/BurnedAreaStats/input/
CorineLandCover:      C:/BurnedAreaStats/data/CORINE2018/CLC_2018_SHP_GR+CY.shp
BSM:                  C:/BurnedAreaStats/data/BSM_1984-2022/bsm_1984_2022.shp
BSM_2023:             C:/BurnedAreaStats/data/BSM2023/BSM_1_1_2023_30_9_2023_TELIKO.shp
Natura2000:           C:/BurnedAreaStats/data/Natura2000/natura2000.shp
Oikismoi:             C:/BurnedAreaStats/data/oikismoi/oikismoi.shp
Periferies:           C:/BurnedAreaStats/data/periphereies/periphereies.shp
Falakro:              C:/BurnedAreaStats/data/falakro/falakro_polygon_classes.shp