OutputFolder_PATH:    ./output/
BurnedAreas_PATH:     ./input/
CorineLandCover:      ./data/CORINE2018/CLC_2018_SHP_GR+CY.shp
BSM:                  ./data/BSM_1984-2022/bsm_1984_2022.shp
BSM_2023:             ./data/BSM2023/BSM_1_1_2023_30_9_2023_TELIKO.shp
Natura2000:           ./data/Natura2000/natura2000.shp
Oikismoi:             ./data/oikismoi/oikismoi.shp
Periferies:           ./data/periphereies/periphereies.shp
Falakro:              ./data/falakro/falakro_polygon_classes.shp