BurnedAreas_PATH:          C:/BurnedAreaStats/input/
OutputFolder_PATH:         C:/BurnedAreaStats/output/
CorineLandCover_PATH:      C:/BurnedAreaStats/data/CORINE2018/CLC_2018_SHP_GR+CY.shp
CorineLandCover_JSON_PATH: configs/Burned_Area_Stats/CLC2018_categories_eng.json
BSM_PATH:                  C:/BurnedAreaStats/data/BSM_1984-2022/bsm_1984_2022.shp
BSM_2023_PATH:             C:/BurnedAreaStats/data/BSM2023/BSM_1_1_2023_30_9_2023_TELIKO.shp
Natura2000_PATH:           C:/BurnedAreaStats/data/Natura2000/natura2000.shp
Oikismoi_PATH:             C:/BurnedAreaStats/data/oikismoi/oikismoi.shp
Periferies_PATH:           C:/BurnedAreaStats/data/periphereies/periphereies.shp
