BurnedAreas_PATH:          /home/sg/Downloads/f66fec325ab04ef6b35ab94be8b9a22d/
OutputFolder_PATH:         /home/sg/Downloads/f66fec325ab04ef6b35ab94be8b9a22d/
CorineLandCover_PATH:      datasets/Corine2018_vectorFromRast.shp
CorineLandCover_JSON_PATH: configs/Burned_Area_Stats/CLC2018_categories_eng.json
BSM_PATH:                  datasets/bsm_1984_2022.shp
BSM_2023_PATH:             datasets/BSM_1_1_2023_30_9_2023_TELIKO.shp
Natura2000_PATH:           datasets/natura_greece.shp
Oikismoi_PATH:             datasets/oikismoi.shp
Periferies_PATH:           datasets/periphereies.shp
